version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-frontend  # Path to the frontend Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Point frontend to backend
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile-backend  # Path to the backend Dockerfile
    ports:
      - "5000:5000"
